dbt_transformation:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/uchennakevinanyanwu/Downloads/bquery_keys_bigstar_collectibles/big-star-collectibles-e-2-e-e854eaca36ff.json
      location:  'US'
      method: service-account
      priority: interactive
      project: big-star-collectibles-e-2-e
      threads: 1
      type: bigquery
  target: dev